name: Github Pages Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and build
        run: npm install && npm run build

      - name: Deploy
        with:
          github_token: ${{ secrets.DEPENDABOT_TOKEN }}
        run: |
          git config --global user.name 'Vasiliy Sushko'
          git config --global user.email 'vasiliy.sushko@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          npm run deploy
